### ISSUE TITLE
Post /donations tiene que devolver un numero de seguimiento para el trackeo 

### ISSUE THREAD

**Issue by abc-recursos** [abcrecursos/abc-recursos-be#2]
Al completar el proceso de la donacion, el donante tiene que recibir un numero de seguimiento.  Esto deberia ser parte del post de una donacion. No se cual es la mejor forma de generar un codigo de seguimiento, pero deberiamos tener un generador de codigo y que ese codigo vuelva de la api al insertar la donacion.

**Comment by abc-recursos** [comment]
El servicio de trackeo permite hacer el seguimiento de una donacion efectuada: saber si esa donacion fue recibida o no. El numero de seguimiento se genero inicialmente al completar una donacion. Se podria implementar como un GET tracking/:id.  El servicio de trackeo tambien le serviria a un solicitante para saber si hubo alguna novedad en relacion a su donacion. Deberiamos permitir que un unico generador de trackingids permita hacer el seguimiento de ambos tipos

**Comment by edvm** [comment]
@abc-recursos creo es suficiente con el id del objeto creado en mongodb (`_id`). Cual es tu opinion?

**Comment by abc-recursos** [comment]
Creo que la única desventaja que le veo es el largo del codigo, que puede ser un poco molesto para anotar y luego ingresar nuevamente. Fuera de eso parece perfecto porque es id unico y ademas serviria para los dos tipos de trackeo (donantes/solicitantes).

**Comment by edvm** [comment]
Otra puede ser algo como: 12-03-2020-46d8 (fecha más los ult 4 chars del objeto creado en mongo).

**Comment by edvm** [comment]
Este issue lo agarro yo :+1
